#!/usr/bin/env python3
from __future__ import annotations
import argparse, json, pathlib, secrets, uuid

def normalize(src, regenerate_unique):
    profile = src.get('profile', src)
    out = json.loads(json.dumps(profile))
    ids = out.setdefault('ids', {})
    if regenerate_unique:
        ids['android_id'] = secrets.token_hex(8)
        ids['boot_id'] = str(uuid.uuid4())
    return out

def generate(profile):
    return "// Generated by Xenoid service Frida generator.\n" + \
"const XENOID_PROFILE = " + json.dumps(profile, ensure_ascii=False, indent=2) + ";\n" + r'''
function log(m) { try { console.log('[xenoid-service] ' + m); } catch (_) {} }
function asInt(v, d) { const n = parseInt(v); return Number.isFinite(n) ? n : d; }

if (Java.available) {
  Java.perform(function () {
    const profile = XENOID_PROFILE;
    const ids = profile.ids || {};
    const build = profile.build || {};
    const battery = profile.battery || {};
    const sensors = profile.sensors || [];

    // Boot ID: app-level Java reads of /proc/sys/kernel/random/boot_id.
    try {
      const BufferedReader = Java.use('java.io.BufferedReader');
      BufferedReader.readLine.implementation = function () {
        const line = this.readLine();
        if (ids.boot_id && line && String(line).match(/^[0-9a-fA-F-]{36}$/)) return String(ids.boot_id);
        return line;
      };
    } catch (e) { log('BufferedReader boot_id hook failed: ' + e); }

    // Settings.Secure android_id.
    try {
      const SettingsSecure = Java.use('android.provider.Settings$Secure');
      SettingsSecure.getString.implementation = function (resolver, name) {
        if (String(name) === 'android_id' && ids.android_id) return String(ids.android_id);
        return this.getString(resolver, name);
      };
    } catch (e) { log('Settings hook failed: ' + e); }

    // System properties and Build fields.
    try {
      const SystemProperties = Java.use('android.os.SystemProperties');
      const props = {
        'ro.product.brand': build.brand,
        'ro.product.manufacturer': build.manufacturer,
        'ro.product.model': build.model,
        'ro.product.device': build.device,
        'ro.product.name': build.product,
        'ro.build.fingerprint': build.fingerprint,
        'ro.hardware': build.hardware,
        'ro.product.board': build.board,
        'persist.sys.locale': profile.locale,
        'persist.sys.timezone': profile.timezone,
        'persist.xenoid.boot_id': ids.boot_id
      };
      SystemProperties.get.overload('java.lang.String').implementation = function (key) {
        const k = String(key); if (props[k] !== undefined && props[k] !== null) return String(props[k]); return this.get(key);
      };
      SystemProperties.get.overload('java.lang.String', 'java.lang.String').implementation = function (key, def) {
        const k = String(key); if (props[k] !== undefined && props[k] !== null) return String(props[k]); return this.get(key, def);
      };
    } catch (e) { log('SystemProperties hook failed: ' + e); }

    try {
      const Build = Java.use('android.os.Build');
      const fields = { BRAND:'brand', MANUFACTURER:'manufacturer', MODEL:'model', DEVICE:'device', PRODUCT:'product', FINGERPRINT:'fingerprint', HARDWARE:'hardware', BOARD:'board' };
      Object.keys(fields).forEach(function (field) { try { const k = fields[field]; if (build[k] !== undefined && Build[field]) Build[field].value = String(build[k]); } catch (_) {} });
    } catch (e) { log('Build hook failed: ' + e); }

    // Battery values returned from ACTION_BATTERY_CHANGED Intent extras.
    try {
      const Intent = Java.use('android.content.Intent');
      Intent.getIntExtra.implementation = function (name, def) {
        const n = String(name).toLowerCase();
        if (n.indexOf('level') >= 0 && battery.level !== undefined) return asInt(battery.level, def);
        if (n.indexOf('scale') >= 0 && battery.scale !== undefined) return asInt(battery.scale, def);
        if (n.indexOf('temperature') >= 0 && battery.temperature !== undefined) return asInt(battery.temperature, def);
        if (n.indexOf('voltage') >= 0 && battery.voltage !== undefined) return asInt(battery.voltage, def);
        if (n.indexOf('plugged') >= 0 && battery.plugged !== undefined) return asInt(battery.plugged, def);
        if (n.indexOf('status') >= 0 && battery.status !== undefined) return asInt(battery.status, def);
        return this.getIntExtra(name, def);
      };
    } catch (e) { log('Battery hook failed: ' + e); }

    // SensorManager list shaping: conservative, returns original list when constructing Sensor is not possible.
    try {
      const SensorManager = Java.use('android.hardware.SensorManager');
      SensorManager.getSensorList.implementation = function (type) {
        const original = this.getSensorList(type);
        if (!sensors || sensors.length === 0) return original;
        // Real Sensor objects are framework-created; this hook documents and centralizes the service point.
        return original;
      };
    } catch (e) { log('SensorManager hook failed: ' + e); }

    log('service/profile hooks loaded');
  });
}
'''

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('profile')
    ap.add_argument('--out', default='.xenoid/frida/generated-service-profile.js')
    ap.add_argument('--keep-unique', action='store_true')
    args=ap.parse_args()
    src=json.loads(pathlib.Path(args.profile).read_text())
    profile=normalize(src, not args.keep_unique)
    out=pathlib.Path(args.out); out.parent.mkdir(parents=True, exist_ok=True); out.write_text(generate(profile))
    print(json.dumps({'ok': True, 'out': str(out), 'android_id': profile.get('ids',{}).get('android_id'), 'boot_id': profile.get('ids',{}).get('boot_id')}, indent=2))
if __name__ == '__main__': main()
