#!/usr/bin/env python3
from __future__ import annotations
import argparse, json, pathlib, secrets, uuid

PROP_MAP = {
    "brand": "BRAND",
    "manufacturer": "MANUFACTURER",
    "model": "MODEL",
    "device": "DEVICE",
    "product": "PRODUCT",
    "fingerprint": "FINGERPRINT",
    "hardware": "HARDWARE",
    "board": "BOARD",
    "bootloader": "BOOTLOADER",
    "id": "ID",
    "tags": "TAGS",
    "type": "TYPE",
}

SYSTEM_PROP_MAP = {
    "brand": "ro.product.brand",
    "manufacturer": "ro.product.manufacturer",
    "model": "ro.product.model",
    "device": "ro.product.device",
    "product": "ro.product.name",
    "fingerprint": "ro.build.fingerprint",
    "hardware": "ro.hardware",
    "board": "ro.product.board",
    "bootloader": "ro.bootloader",
    "tags": "ro.build.tags",
    "type": "ro.build.type",
}

def normalize(src: dict, regenerate_unique: bool) -> dict:
    profile = src.get("profile", src)
    out = json.loads(json.dumps(profile))
    ids = out.setdefault("ids", {})
    if regenerate_unique:
        ids["android_id"] = secrets.token_hex(8)
        ids["boot_id"] = str(uuid.uuid4())
    return out

def js_string(s): return json.dumps(str(s))

def generate(profile: dict) -> str:
    build = profile.get("build", {}) or {}
    ids = profile.get("ids", {}) or {}
    battery = profile.get("battery", {}) or {}
    locale = profile.get("locale")
    timezone = profile.get("timezone")
    system_props = {}
    for k, prop in SYSTEM_PROP_MAP.items():
        if k in build and build[k] is not None:
            system_props[prop] = str(build[k])
    if locale: system_props["persist.sys.locale"] = str(locale)
    if timezone: system_props["persist.sys.timezone"] = str(timezone)
    if ids.get("boot_id") and ids["boot_id"] != "REGENERATE":
        system_props["persist.xenoid.boot_id"] = str(ids["boot_id"])
    lines = []
    lines.append("// Generated by Xenoid. Do not edit manually.")
    lines.append("const XENOID_PROFILE = " + json.dumps(profile, ensure_ascii=False, indent=2) + ";")
    lines.append("const XENOID_SYSTEM_PROPS = " + json.dumps(system_props, ensure_ascii=False, indent=2) + ";")
    lines.append(r'''
function xenoidLog(msg) { try { console.log('[xenoid-profile] ' + msg); } catch (_) {} }
function xenoidConcrete(value) { return value !== undefined && value !== null && String(value) !== 'REGENERATE'; }
if (Java.available) {
  Java.perform(function () {
    const profile = XENOID_PROFILE;
    const build = profile.build || {};
    const ids = profile.ids || {};
    const battery = profile.battery || {};
    try {
      const Build = Java.use('android.os.Build');
      const map = {
        brand: 'BRAND', manufacturer: 'MANUFACTURER', model: 'MODEL', device: 'DEVICE',
        product: 'PRODUCT', fingerprint: 'FINGERPRINT', hardware: 'HARDWARE', board: 'BOARD',
        bootloader: 'BOOTLOADER', id: 'ID', tags: 'TAGS', type: 'TYPE'
      };
      Object.keys(map).forEach(function (k) { try { if (build[k] !== undefined && Build[map[k]]) Build[map[k]].value = String(build[k]); } catch (_) {} });
    } catch (e) { xenoidLog('Build hook failed: ' + e); }

    try {
      const SystemProperties = Java.use('android.os.SystemProperties');
      SystemProperties.get.overload('java.lang.String').implementation = function (key) {
        const k = String(key);
        if (XENOID_SYSTEM_PROPS[k] !== undefined) return String(XENOID_SYSTEM_PROPS[k]);
        return this.get(key);
      };
      SystemProperties.get.overload('java.lang.String', 'java.lang.String').implementation = function (key, def) {
        const k = String(key);
        if (XENOID_SYSTEM_PROPS[k] !== undefined) return String(XENOID_SYSTEM_PROPS[k]);
        return this.get(key, def);
      };
    } catch (e) { xenoidLog('SystemProperties hook failed: ' + e); }

    try {
      const SettingsSecure = Java.use('android.provider.Settings$Secure');
      SettingsSecure.getString.implementation = function (resolver, name) {
        if (String(name) === 'android_id' && xenoidConcrete(ids.android_id)) return String(ids.android_id);
        return this.getString(resolver, name);
      };
    } catch (e) { xenoidLog('Settings.Secure hook failed: ' + e); }

    try {
      const TimeZone = Java.use('java.util.TimeZone');
      TimeZone.getDefault.implementation = function () {
        if (profile.timezone) return TimeZone.getTimeZone(String(profile.timezone));
        return this.getDefault();
      };
    } catch (e) { xenoidLog('Timezone hook failed: ' + e); }

    try {
      const Intent = Java.use('android.content.Intent');
      Intent.getIntExtra.implementation = function (name, def) {
        const n = String(name);
        if (n.indexOf('level') >= 0 && battery.level !== undefined) return parseInt(battery.level);
        if (n.indexOf('scale') >= 0 && battery.scale !== undefined) return parseInt(battery.scale);
        if (n.indexOf('temperature') >= 0 && battery.temperature !== undefined) return parseInt(battery.temperature);
        if (n.indexOf('voltage') >= 0 && battery.voltage !== undefined) return parseInt(battery.voltage);
        if (n.indexOf('plugged') >= 0 && battery.plugged !== undefined) return parseInt(battery.plugged);
        return this.getIntExtra(name, def);
      };
    } catch (e) { xenoidLog('Battery intent hook failed: ' + e); }

    xenoidLog('profile spoof hooks loaded');
  });
}
''')
    return "\n".join(lines)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("profile")
    ap.add_argument("--out", default=".xenoid/frida/generated-profile.js")
    ap.add_argument("--keep-unique", action="store_true")
    args = ap.parse_args()
    src = json.loads(pathlib.Path(args.profile).read_text())
    profile = normalize(src, regenerate_unique=not args.keep_unique)
    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(generate(profile))
    print(json.dumps({"ok": True, "out": str(out), "android_id": profile.get("ids", {}).get("android_id"), "boot_id": profile.get("ids", {}).get("boot_id")}, indent=2))
if __name__ == "__main__": main()
